### ISSUE TITLE
Show component for Legislation

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#113]
## demogra / Legislation

Implement a component to show information for: 

```javascript
legislationAtomizedType = {
	legislationName: '',
	protectionLegalStatus: '',
	legislationRead: '',
	status: '',
	type: '',
	norm: '',
	appliesTo: {
		country: '',
		stateProvince: '',
		county: '',
		municipality: '',
		locality: ''
	},
	ancillaryData: []
};

legislation = {
	legislationAtomized: [],
	legislationUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/LegislationClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra los detalles del issue se dan en #236
