### ISSUE TITLE
Show component for Territory

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#117]
## demogra / Territory

Implement a component to show information for: 

```javascript
territory = {
	territoryAtomized: {
		extentOfOccurrence: '',
		areaOfOccupancy: ''
	},
	territoryUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/TerritoryClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra los detalles del issue se dan en #243
