### ISSUE TITLE
Show component for Measurement

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#121]
## form / Measurement

Implement a component to show information for: 

```javascript
measurement = {
	measurementOrFact : {
		measurementID: '',
		measurementType: '',
		measurementValue: '',
		measurementAccuracy: '',
		measurementUnit: '',
		measurementDeterminedDate: '',
		measurementDeterminedBy: [],
		measurementMethod: '',
		measurementRemarks: '',
		relatedTo: ''
	},
	ancillaryData : {
		identifier:'',
		dataType:'',
		mimeType:'',
		agent:[],
		created:'',
		modified:'',
		license:'',
		rights:'',
		rightsHolder:'',
		bibliographicCitation:'',
		audience:[],
		source:'',
		subject:[],
		description:'',
		mediaURL:[],
		thumbnailURL:'',
		location:'',
		geoPoint:'',
		reference:[],
		additionalInformation:'',
		dataObject:''
	}
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/MeasurementClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
@camiplata por validar, identificar una ficha con la información documentada

**Comment by camiplata** [comment]
Mamut no incluye esta clase del Plinian.
Esta clase ya no se debe implementar; en la última versión del perfil de aplicación fue eliminada ya que la información debe venir de los datos.

FYI @leobuitrago @javiesgm
