### ISSUE TITLE
Show component for Distribution

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#123]
## habitad / Distribution

Implement a component to show information for: 

```javascript
distributionOpt2 = {
	country: 'Colombia',
	stateProvince: '',
	county: '',
	municipality: '',
	locality: '',
	ancillaryData: []
};

distributionClass = {
	distributionScope: {
		type: '',
		ancillaryData: []
	},
	temporalCoverage: {
		startDate: '',
		endDate: ''
	},
	distributionAtomized: [],
	distributionUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/DistributionClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra los detalles del issue se dan en #233 #243
