### ISSUE TITLE
Show component for Endemic

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#125]
## habitad / Endemic

Implement a component to show information for: 

```javascript
endemicAtomizedType = {
	endemicTo: [],
	endemicIn: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/EndemicClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
@camiplata por validar, identificar una ficha con la información documentada

**Comment by camiplata** [comment]
No se puede validar si el elemento fue implementado, ver detalles en #257
