### ISSUE TITLE
Show component for Habitats

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#127]
## habitad / Habitats

Implement a component to show information for: 

```javascript
habitat = {
	habitatAtomized: [],
	habitatUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/HabitatsClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra los detalles del issue se dan en #233
