### ISSUE TITLE
Show component for AnnualCycle

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#129]
## history / AnnualCycle

Implement a component to show information for: 

```javascript
annualCycleAtomizedType = {
	Event: '',
	startTimeInterval: '',
	endTimeInterval: '',
	ancillaryData: []
};

annualCycle = {
	annualCycleAtomized: [],
	annualCycleUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/AnnualCycleClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Mamut no incluye esta clase del Plinian.
Esta clase ya no se debe implementar; en la última versión del perfil de aplicación fue eliminada ya que la información se puede contener en la clase ciclo de vida.

FYI @leobuitrago @javiesgm
