### ISSUE TITLE
Show component for EcologicalSignificance

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#135]
## history / EcologicalSignificance

Implement a component to show information for: 

```javascript
ecologicalSignificance = {
	ecologicalSignificanceAtomized: [],
	ecologicalSignificanceUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/EcologicalSignificanceClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
@camiplata por validar, identificar una ficha con la información documentada
