### ISSUE TITLE
Show component for EnvironmentalEnvelope

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#137]
## history / EnvironmentalEnvelope

Implement a component to show information for: 

```javascript
environmentalEnvelope = {
	environmentalEnvelopeAtomized: [],
	environmentalEnvelopeUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/EnvironmentalEnvelopeClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
@camiplata por validar, identificar una ficha con la información documentada
