### ISSUE TITLE
Show component for Feeding

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#139]
## history / Feeding

Implement a component to show information for: 

```javascript
thropic = {
	strategy: '',
	strategyRemarks: ''
};

feedingAtomizedType = {
	type: '',
	thropic: [],
	ancillaryData: []
};

feeding = {
	feedingAtomized: [],
	feedingUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/FeedingClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra, los detalles del issue se dan en #241
