### ISSUE TITLE
Show component for Migratory

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#147]
## history / Migratory

Implement a component to show information for: 

```javascript
migratoryAtomizedType = {
	causes: '',
	patterns: '',
	routes: [],
	season: '',
	ancillaryData: []
};

migratory = {
	migratoryAtomized: [],
	migratoryUnstructured: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/MigratoryClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra, los detalles del issue pertinente se dan en #255
