### ISSUE TITLE
Show component for CommonName

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#155]
## nomeAndClass / CommonName

Implement a component to show information for: 

```javascript
commonName = {
	name: '',
	language: '',
	usedIn: {
		distributionScope: {
			type: '',
			ancillaryData: []
		},
		temporalCoverage: {
			startDate: '',
			endDate: ''
		},
		distributionAtomizedBranch: [],
		distributionUnstructured: '',
		ancillaryData: []
	},
	usedBy: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/CommonNameClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra, los detalles del issue peritnente se dan en #239
