### ISSUE TITLE
Show component for Uses

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#171]
## uses / Uses

Implement a component to show information for: 

```javascript
usesAtomizedType = {
	sourceOfInformation: {
		references: [],
		sourceOfInformationText: ''
	},
	useValue: '',
	partUsed: '',
	users: '',
	organisms: '',
	vernacularNameUseAnnotations: '',
	productionDetails: '',
	meansOfApplicationAdministration: '',
	seasonOfAvailabilityUse: '',
	conservationExplotationData: '',
	useTypeAtomized: '',
	economics: '',
	ratingPopularity: '',
	properties: '',
	potential: '',
	useNotes: '',
	ancillaryData: []
};
```

The class specification can be found in https://github.com/tdwg/PlinianCore/wiki/UsesClass

The general documentation of Plinian Core can be found in https://github.com/tdwg/PlinianCore/wiki

**Comment by camiplata** [comment]
Implementado pero tiene errores, se cierra, los detalles del issue pertinente se dan en #244
