### ISSUE TITLE
Footer - Tamaño de texto

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/catalogo-de-la-biodiversidad-frontend#174]
Sugiero disminuir el grosor y el tamaño de la fuente para el contenido del pie de página y cambiar a blanco el color de las líneas divisoras.

Adjunto imagen de ejemplo:  

![captura de pantalla 2017-05-11 a la s 7 29 48 p m](https://cloud.githubusercontent.com/assets/14220404/25977312/60b94272-3680-11e7-8d8f-671c5bb5ac68.png)

**Comment by javiesgm** [comment]
Sugiero que el "peso" de la fuente sea 300. Eliminar el BOLD de los enlaces en el pie de página.

**Comment by camiplata** [comment]
@dapino para tu revisión
